language: node_js
node_js:
  - "6"

branches:
  only:
    - master
    - develop

before_script:
  - nohup node tests/server.js &

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage